-- =============================================
-- TABLA: bloqueos_horario
-- El dueño del taller puede bloquear días completos
-- o franjas horarias específicas para que no aparezcan
-- como disponibles en la vista pública.
-- =============================================

create table if not exists public.bloqueos_horario (
  id bigint generated by default as identity primary key,
  fecha date not null,
  hora time,              -- NULL = día completo bloqueado
  motivo text,
  created_at timestamptz not null default now()
);

-- Índice para búsquedas rápidas por fecha
create index if not exists idx_bloqueos_fecha on public.bloqueos_horario(fecha);

-- Evitar duplicados: misma fecha + hora
create unique index if not exists idx_bloqueos_fecha_hora
  on public.bloqueos_horario(fecha, hora)
  where hora is not null;

-- Evitar duplicar bloqueo de día completo
create unique index if not exists idx_bloqueos_fecha_dia_completo
  on public.bloqueos_horario(fecha)
  where hora is null;

alter table public.bloqueos_horario enable row level security;

drop policy if exists "Public can read bloqueos" on public.bloqueos_horario;
create policy "Public can read bloqueos"
on public.bloqueos_horario for select to anon using (true);

drop policy if exists "Public can insert bloqueos" on public.bloqueos_horario;
create policy "Public can insert bloqueos"
on public.bloqueos_horario for insert to anon with check (true);

drop policy if exists "Public can delete bloqueos" on public.bloqueos_horario;
create policy "Public can delete bloqueos"
on public.bloqueos_horario for delete to anon using (true);
