-- =============================================
-- TABLA: clientes
-- =============================================
create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  telefono text,
  email text,
  direccion text,
  created_at timestamptz not null default now()
);

alter table public.clientes enable row level security;

drop policy if exists "Public can read clientes" on public.clientes;
create policy "Public can read clientes"
on public.clientes for select to anon using (true);

drop policy if exists "Public can insert clientes" on public.clientes;
create policy "Public can insert clientes"
on public.clientes for insert to anon with check (true);

drop policy if exists "Public can update clientes" on public.clientes;
create policy "Public can update clientes"
on public.clientes for update to anon using (true) with check (true);

-- =============================================
-- TABLA: vehiculos
-- =============================================
create table if not exists public.vehiculos (
  id bigint generated by default as identity primary key,
  cliente_id bigint references public.clientes(id) on delete cascade,
  marca text not null,
  modelo text not null,
  anio integer,
  placa text not null,
  color text,
  created_at timestamptz not null default now()
);

alter table public.vehiculos enable row level security;

drop policy if exists "Public can read vehiculos" on public.vehiculos;
create policy "Public can read vehiculos"
on public.vehiculos for select to anon using (true);

drop policy if exists "Public can insert vehiculos" on public.vehiculos;
create policy "Public can insert vehiculos"
on public.vehiculos for insert to anon with check (true);

drop policy if exists "Public can update vehiculos" on public.vehiculos;
create policy "Public can update vehiculos"
on public.vehiculos for update to anon using (true) with check (true);

-- =============================================
-- TABLA: ordenes
-- =============================================
create table if not exists public.ordenes (
  id bigint generated by default as identity primary key,
  cliente_id bigint references public.clientes(id) on delete set null,
  vehiculo_id bigint references public.vehiculos(id) on delete set null,
  descripcion text,
  costo_estimado numeric(10,2),
  estado text not null default 'pendiente'
    check (estado in ('pendiente', 'en_proceso', 'completada', 'cancelada')),
  notas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.ordenes enable row level security;

drop policy if exists "Public can read ordenes" on public.ordenes;
create policy "Public can read ordenes"
on public.ordenes for select to anon using (true);

drop policy if exists "Public can insert ordenes" on public.ordenes;
create policy "Public can insert ordenes"
on public.ordenes for insert to anon with check (true);

drop policy if exists "Public can update ordenes" on public.ordenes;
create policy "Public can update ordenes"
on public.ordenes for update to anon using (true) with check (true);

drop policy if exists "Public can delete ordenes" on public.ordenes;
create policy "Public can delete ordenes"
on public.ordenes for delete to anon using (true);
