create table if not exists public.solicitudes_publicas (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('atencion', 'cotizacion')),
  estado text not null default 'pendiente' check (estado in ('pendiente', 'en_proceso', 'cerrada')),
  nombre text not null,
  telefono text not null,
  email text,
  patente text,
  servicio text,
  mensaje text,
  marca text,
  modelo text,
  anio integer,
  trabajo text,
  created_at timestamptz not null default now()
);

alter table public.solicitudes_publicas
add column if not exists estado text;

update public.solicitudes_publicas
set estado = 'pendiente'
where estado is null;

alter table public.solicitudes_publicas
alter column estado set default 'pendiente';

alter table public.solicitudes_publicas
alter column estado set not null;

alter table public.solicitudes_publicas
drop constraint if exists solicitudes_publicas_estado_check;

alter table public.solicitudes_publicas
add constraint solicitudes_publicas_estado_check
check (estado in ('pendiente', 'en_proceso', 'cerrada'));

alter table public.solicitudes_publicas enable row level security;

drop policy if exists "Public can insert solicitudes"
on public.solicitudes_publicas;

create policy "Public can insert solicitudes"
on public.solicitudes_publicas
for insert
to anon
with check (true);

drop policy if exists "Public can read solicitudes"
on public.solicitudes_publicas;

create policy "Public can read solicitudes"
on public.solicitudes_publicas
for select
to anon
using (true);

drop policy if exists "Public can update solicitudes status"
on public.solicitudes_publicas;

create policy "Public can update solicitudes status"
on public.solicitudes_publicas
for update
to anon
using (true)
with check (true);
